// <auto-generated />
using HamsterWarsApi.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamsterWarsApi.Server.Migrations
{
    [DbContext(typeof(HamsterWars2DbContext))]
    partial class HamsterWars2DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HamsterWarsApi.Shared.Models.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LoserId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("HamsterWarsApi.Shared.Models.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FavFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<string>("ImgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Loves")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 1,
                            FavFood = "Apples",
                            Games = 0,
                            ImgName = "/images/hamster-1.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Belle",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            FavFood = "Bananas",
                            Games = 0,
                            ImgName = "/images/hamster-2.jpg",
                            Losses = 0,
                            Loves = "Snuggleing",
                            Name = "Cleo",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            FavFood = "Broccoli",
                            Games = 0,
                            ImgName = "/images/hamster-3.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Name = "Evie",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 4,
                            FavFood = "Carrots",
                            Games = 0,
                            ImgName = "/images/hamster-4.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Lola",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 1,
                            FavFood = "Strawberries",
                            Games = 0,
                            ImgName = "/images/hamster-5.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Daisy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            FavFood = "BlueBerries",
                            Games = 0,
                            ImgName = "/images/hamster-6.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Penny",
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            Age = 3,
                            FavFood = "Peanuts",
                            Games = 0,
                            ImgName = "/images/hamster-7.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Ivy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            Age = 4,
                            FavFood = "Potato",
                            Games = 0,
                            ImgName = "/images/hamster-8.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Roxy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            Age = 2,
                            FavFood = "Seeds",
                            Games = 0,
                            ImgName = "/images/hamster-9.jpg",
                            Losses = 0,
                            Loves = "Snuggleing",
                            Name = "Zoe",
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            Age = 1,
                            FavFood = "Grapes",
                            Games = 0,
                            ImgName = "/images/hamster-10.jpg",
                            Losses = 0,
                            Loves = "Snuggleing",
                            Name = "Duncan",
                            Wins = 0
                        },
                        new
                        {
                            Id = 11,
                            Age = 2,
                            FavFood = "Banana",
                            Games = 0,
                            ImgName = "/images/hamster-11.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Frodo",
                            Wins = 0
                        },
                        new
                        {
                            Id = 12,
                            Age = 3,
                            FavFood = "Strawberries",
                            Games = 0,
                            ImgName = "/images/hamster-12.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Name = "Jasper",
                            Wins = 0
                        },
                        new
                        {
                            Id = 13,
                            Age = 4,
                            FavFood = "Spinach",
                            Games = 0,
                            ImgName = "/images/hamster-13.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Jojo",
                            Wins = 0
                        },
                        new
                        {
                            Id = 14,
                            Age = 1,
                            FavFood = "Hay",
                            Games = 0,
                            ImgName = "/images/hamster-14.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Max",
                            Wins = 0
                        },
                        new
                        {
                            Id = 15,
                            Age = 2,
                            FavFood = "Broccoli",
                            Games = 0,
                            ImgName = "/images/hamster-15.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Name = "Gomez",
                            Wins = 0
                        },
                        new
                        {
                            Id = 16,
                            Age = 3,
                            FavFood = "Carrot",
                            Games = 0,
                            ImgName = "/images/hamster-16.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Felix",
                            Wins = 0
                        },
                        new
                        {
                            Id = 17,
                            Age = 4,
                            FavFood = "Apples",
                            Games = 0,
                            ImgName = "/images/hamster-17.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Frodo",
                            Wins = 0
                        },
                        new
                        {
                            Id = 18,
                            Age = 5,
                            FavFood = "Cucumber",
                            Games = 0,
                            ImgName = "/images/hamster-18.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Rocky",
                            Wins = 0
                        },
                        new
                        {
                            Id = 19,
                            Age = 2,
                            FavFood = "Apples",
                            Games = 0,
                            ImgName = "/images/hamster-19.jpg",
                            Losses = 0,
                            Loves = "Snuggleing",
                            Name = "Frizy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 20,
                            Age = 5,
                            FavFood = "Cucumber",
                            Games = 0,
                            ImgName = "/images/hamster-20.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Nemo",
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
